'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("USB_Security.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1_1_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1_1_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1_2_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1_2_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1_3_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1_3_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2_1_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2_1_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2_2_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2_2_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2_3_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2_3_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3_1_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_3_1_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3_2_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_3_2_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3_3_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_3_3_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4_1_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_4_1_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4_2_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_4_2_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4_3_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_4_3_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5_1_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_5_1_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5_2_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_5_2_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5_3_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_5_3_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6_1_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_6_1_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6_2_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_6_2_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6_3_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_6_3_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _7_1_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_7_1_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _7_2_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_7_2_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _7_3_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_7_3_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _8_1_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_8_1_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _8_2_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_8_2_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _8_3_fw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_8_3_fw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a [general]
        '''checkStartSystem=False
        '''checkOpenDevice=False
        '''checkCreateProtUSB=True
        '''checkCreateProtHDD=False
        '''checkDisableExecAutom=True
        '''checkShowFFHidden=True
        '''checkCopyLastUpdate=False
        '''checkFindNewsUpdates=False
        '''comboDetectMalware=1
        '''comboDetectFilesSuspect=2
        '''
        '''[registro]
        '''checkAmenazasDetect=True
        '''checkDisposConect=True
        '''checkExplorePC=True
        '''checkSucesos=True
        '''numRegSizeQuar=100
        '''
        '''[notificacion]
        '''checkAlertMess=True
        '''checkNoUpdated=True
        '''checkUpdatedSuccess=True
        '''checkFilesMoveToQuar=True
        '''checkResul [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property config() As String
            Get
                Return ResourceManager.GetString("config", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property config1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("config1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_logs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_logs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_scan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_scan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_settings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_settings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_update() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_update", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        '''</summary>
        Friend ReadOnly Property ic_update1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_update1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        '''</summary>
        Friend ReadOnly Property icon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("icon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_success() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_success", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_warn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_warn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property secur001() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("secur001", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property secur002() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("secur002", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property secur006() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("secur006", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property secur007() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("secur007", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property security00() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("security00", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property security01() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("security01", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
